//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2013.08.26 at 05:10:19 PM NOVT
//


package training.data;

import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import training.parser.jsonparser.JacksonCarBuilder;
import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;

import javax.xml.bind.annotation.*;


/**
 * Java class for Car complex type.
 *
 */
@XmlRootElement(name = "car")
@XmlAccessorType(XmlAccessType.FIELD)
@JsonDeserialize(builder = JacksonCarBuilder.class)
public class Car {

    @XmlElement(required = true, defaultValue = "Unknown")
    private String number = "";


    /**
     * Gets the value of the number property.
     *
     * @return number.
     *
     */
    public String getNumber() {
        return number;
    }

    /**
     * Sets the value of the number property.
     *
     * @param value number
     *
     */
    public void setNumber(final String value) {
        this.number = value;
    }

    @Override
    public boolean equals(final Object other) {
        if (other == null) {
            return false;
        }
        if (other == this) {
            return true;
        }
        if (!(other instanceof Car)) {
            return false;
        }

        final Car otherAddr = (Car) other;
        return new EqualsBuilder()
            .append(number, otherAddr.number)
            .isEquals();
    }

    @Override
    public int hashCode() {
        return new HashCodeBuilder()
            .append(number)
            .toHashCode();
    }


}
