//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2013.08.26 at 05:10:19 PM NOVT
//


package training.data;

import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import training.parser.jsonparser.JacksonCarsListBuilder;
import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.*;


/**
 * Java class for Cars complex type.
 *
 */


@XmlRootElement(name = "cars")
@XmlAccessorType(XmlAccessType.FIELD)
@JsonDeserialize(builder = JacksonCarsListBuilder.class)
public class Cars {
    @XmlElement(name = "car")
    private final List<Car> cars = new ArrayList<Car>();


    public List<Car> getCars() {
        return this.cars;
    }

    public void setCars(final Car cars) {
        getCars().add(cars);
    }

    @Override
    public boolean equals(final Object other) {
        if (other == null) {
            return false;
        }
        if (other == this) {
            return true;
        }
        if (!(other instanceof Cars)) {
            return false;
        }

        final Cars otherAddrList = (Cars) other;
        return new EqualsBuilder()
            .append(cars, otherAddrList.cars)
            .isEquals();
    }

    @Override
    public int hashCode() {
        return new HashCodeBuilder()
            .append(cars)
            .toHashCode();
    }

}
